# Generated by Django 6.0.5 on 2026-05-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='templates/')),
                ('action_type', models.CharField(default='fill', max_length=50)),
                ('fill_color', models.CharField(default='#ffffff', max_length=20)),
                ('padding', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='limpador.processedimage')),
            ],
        ),
    ]
