# Generated by Django 6.0.5 on 2026-05-14 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpador', '0002_imagetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagetemplate',
            name='processed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='limpador.processedimage'),
        ),
    ]
