# Generated by Django 6.0.5 on 2026-05-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limpador', '0003_alter_imagetemplate_processed_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetemplate',
            name='original_width',
            field=models.IntegerField(default=0),
        ),
    ]
